CREATE TABLE 'user' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'email' TEXT DEFAULT NULL,
'password_encrypted' TEXT DEFAULT NULL,
'authenticated' INTEGER DEFAULT NULL,
'email_code' TEXT DEFAULT NULL,
UNIQUE (email)
);

CREATE TABLE 'seller' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id')
);

CREATE TABLE 'product' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'seller_id' INTEGER DEFAULT NULL REFERENCES 'seller' ('id'),
'buy' INTEGER DEFAULT NULL,
'auction' INTEGER DEFAULT NULL,
'shipping_days' INTEGER DEFAULT NULL
);

CREATE TABLE 'shipment' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'tracking_url' TEXT DEFAULT NULL,
'new field' INTEGER DEFAULT NULL
);

CREATE TABLE 'review' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id'),
'stars' INTEGER DEFAULT NULL,
'headline' TEXT DEFAULT NULL,
'text_html' TEXT DEFAULT NULL
);

CREATE TABLE 'wishlist' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'name' TEXT DEFAULT NULL
);

CREATE TABLE 'cart' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'active' INTEGER DEFAULT NULL,
'purchased' INTEGER DEFAULT NULL
);

CREATE TABLE 'address' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'full_name' TEXT DEFAULT NULL,
'address_line_1' TEXT DEFAULT NULL,
'address_line_2' TEXT DEFAULT NULL,
'city' TEXT DEFAULT NULL,
'state' TEXT DEFAULT NULL,
'zip' INTEGER DEFAULT NULL,
'country_id' INTEGER DEFAULT NULL REFERENCES 'country' ('id')
);

CREATE TABLE 'feedback' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'cart_item_id' INTEGER DEFAULT NULL REFERENCES 'cart_item' ('id'),
'stars' INTEGER DEFAULT NULL,
'arrived_on_time' INTEGER DEFAULT NULL,
'correctly_described' INTEGER DEFAULT NULL,
'prompt_service' INTEGER DEFAULT NULL,
'comments' TEXT DEFAULT NULL
);

CREATE TABLE 'cart_item' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'cart_id' INTEGER DEFAULT NULL REFERENCES 'cart' ('id'),
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id'),
'quantity' INTEGER DEFAULT NULL,
'purchased' INTEGER DEFAULT NULL
);

CREATE TABLE 'payment' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'seller_id' INTEGER DEFAULT NULL
);

CREATE TABLE 'bid' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'auction_id' INTEGER DEFAULT NULL REFERENCES 'auction' ('id'),
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'amount' INTEGER DEFAULT NULL,
'time' INTEGER DEFAULT NULL
);

CREATE TABLE 'auction' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id'),
'expire_time' INTEGER DEFAULT NULL,
'start_amount' NUMERIC DEFAULT NULL,
'currency_id' INTEGER DEFAULT NULL REFERENCES 'currency' ('id'),
'reserve_amount' INTEGER DEFAULT NULL
);

CREATE TABLE 'currency' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'desc' TEXT DEFAULT NULL,
'iso' TEXT DEFAULT NULL,
'unicode' TEXT DEFAULT NULL
);

CREATE TABLE 'country' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'name' TEXT DEFAULT NULL
);

CREATE TABLE 'cart_item_payment' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'cart_item_id' INTEGER DEFAULT NULL REFERENCES 'cart_item' ('id'),
'payment_id' INTEGER DEFAULT NULL REFERENCES 'payment' ('id')
);

CREATE TABLE 'cart_item_shipment' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'cart_item_id' INTEGER DEFAULT NULL REFERENCES 'cart_item' ('id'),
'shipment_id' INTEGER DEFAULT NULL REFERENCES 'shipment' ('id')
);

CREATE TABLE 'review_vote' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'review_id' INTEGER DEFAULT NULL REFERENCES 'review' ('id'),
'vote' NUMERIC DEFAULT NULL,
UNIQUE (user_id, review_id)
);

CREATE TABLE 'review_comment' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'review_id' INTEGER DEFAULT NULL REFERENCES 'review' ('id'),
'comment' TEXT DEFAULT NULL
);

CREATE TABLE 'question' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id'),
'text' TEXT DEFAULT NULL
);

CREATE TABLE 'answer' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'question_id' INTEGER DEFAULT NULL REFERENCES 'question' ('id'),
'text' TEXT DEFAULT NULL
);

CREATE TABLE 'question_vote' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'question_id' INTEGER DEFAULT NULL REFERENCES 'question' ('id'),
'user_id' INTEGER DEFAULT NULL,
'vote' NUMERIC DEFAULT NULL
);

CREATE TABLE 'answer_vote' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'answer_id' INTEGER DEFAULT NULL REFERENCES 'answer' ('id'),
'vote' NUMERIC DEFAULT NULL
);

CREATE TABLE 'category' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'name' TEXT DEFAULT NULL,
'parent' INTEGER DEFAULT NULL
);

CREATE TABLE 'product_category' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id'),
'category_id' INTEGER DEFAULT NULL REFERENCES 'category' ('id')
);

CREATE TABLE 'wishlist_item' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'wishlist_id' INTEGER DEFAULT NULL REFERENCES 'wishlist' ('id'),
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id'),
'purchased' INTEGER DEFAULT NULL
);

CREATE TABLE 'login' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'user_id' INTEGER DEFAULT NULL REFERENCES 'user' ('id'),
'session_id' TEXT DEFAULT NULL,
'time_' INTEGER DEFAULT NULL,
'expire_time' INTEGER DEFAULT NULL
);

CREATE TABLE 'product_price' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id'),
'price' INTEGER DEFAULT NULL,
'currency_id' INTEGER DEFAULT NULL REFERENCES 'currency' ('id'),
'variable_price' INTEGER DEFAULT NULL,
'price_select' INTEGER DEFAULT NULL
);

CREATE TABLE 'price_list' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'product_price_id' INTEGER DEFAULT NULL REFERENCES 'product_price' ('id'),
'price' INTEGER DEFAULT NULL,
'currency_id' INTEGER DEFAULT NULL REFERENCES 'currency' ('id')
);

CREATE TABLE 'product_group' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE 'product_group_item' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'product_group' INTEGER DEFAULT NULL REFERENCES 'product_group' ('id'),
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id')
);

CREATE TABLE 'product_page' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id'),
'product_html' TEXT DEFAULT NULL
);

CREATE TABLE 'product_thumbnail' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'product_id' INTEGER DEFAULT NULL REFERENCES 'product' ('id'),
'image_loc' TEXT DEFAULT NULL
);

CREATE INDEX '' ON 'address' ('');
